---
- hosts: jumpbox
  gather_facts: true
  roles:
  - name: osp_gather_facts
# setup application load balancer

- name: setup load-balancer
  hosts: frontends
  gather_facts: false
  become: yes
  roles:
     - {name: haproxy}

# setup application deployment

- name: setup app deployment
  hosts: apps
  gather_facts: false
  become: yes
  roles:
     - {name: tomcat}

# setup backend database 

- name: setup database deployment
  hosts: appdbs
  gather_facts: true
  become: yes
  become_user: root
  roles:
     - {name: geerlingguy.postgresql}

